name: Build Executables

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows
            ext: .exe
            separator: ";"
          - os: macos-latest  
            name: macos
            ext: .app
            separator: ":"
          - os: ubuntu-latest
            name: linux
            ext: ""
            separator: ":"
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.10.0
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos${{ matrix.separator }}google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    
    - name: Prepare release file (Windows)
      if: matrix.name == 'windows'
      run: |
        mv dist/GoogleTakeoutHelper.exe GoogleTakeoutHelper.exe
    
    - name: Prepare release file (macOS)
      if: matrix.name == 'macos'
      run: |
        zip -r GoogleTakeoutHelper-macOS.zip dist/GoogleTakeoutHelper.app
    
    - name: Prepare release file (Linux)
      if: matrix.name == 'linux'
      run: |
        mv dist/GoogleTakeoutHelper GoogleTakeoutHelper-linux
    
    - name: Upload release assets
      if: github.event_name == 'release'
      run: |
        if [ "${{ matrix.name }}" = "windows" ]; then
          gh release upload ${{ github.event.release.tag_name }} GoogleTakeoutHelper.exe
        elif [ "${{ matrix.name }}" = "macos" ]; then
          gh release upload ${{ github.event.release.tag_name }} GoogleTakeoutHelper-macOS.zip
        elif [ "${{ matrix.name }}" = "linux" ]; then
          gh release upload ${{ github.event.release.tag_name }} GoogleTakeoutHelper-linux
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
