name: Build and Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos;google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    
    - name: Build executable (macOS/Linux)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos:google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    
    - name: Prepare Windows artifact
      if: matrix.os == 'windows-latest'
      run: |
        mv dist/GoogleTakeoutHelper.exe GoogleTakeoutHelper.exe
    
    - name: Prepare macOS artifact
      if: matrix.os == 'macos-latest'
      run: |
        zip -r GoogleTakeoutHelper-macOS.zip dist/GoogleTakeoutHelper.app
    
    - name: Prepare Linux artifact
      if: matrix.os == 'ubuntu-latest'
      run: |
        mv dist/GoogleTakeoutHelper GoogleTakeoutHelper-linux
    
    - name: Upload Windows executable
      if: matrix.os == 'windows-latest' && github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: GoogleTakeoutHelper.exe
    
    - name: Upload macOS executable
      if: matrix.os == 'macos-latest' && github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: GoogleTakeoutHelper-macOS.zip
    
    - name: Upload Linux executable
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: GoogleTakeoutHelper-linux
