name: Build Executables

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos;google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    - name: Upload Windows executable
      uses: softprops/action-gh-release@v2
      with:
        files: dist/GoogleTakeoutHelper.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos:google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    - name: Zip macOS app
      run: |
        zip -r GoogleTakeoutHelper-macOS.zip dist/GoogleTakeoutHelper.app
    - name: Upload macOS executable
      uses: softprops/action-gh-release@v2
      with:
        files: GoogleTakeoutHelper-macOS.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos:google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    - name: Upload Linux executable
      uses: softprops/action-gh-release@v2
      with:
        files: dist/GoogleTakeoutHelper
