name: Build Executables

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.0.0
    
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos;google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    
    - name: Upload Windows executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} dist/GoogleTakeoutHelper.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.0.0
    
    - name: Build macOS executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos:google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
        zip -r GoogleTakeoutHelper-macOS.zip dist/GoogleTakeoutHelper.app
    
    - name: Upload macOS executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} GoogleTakeoutHelper-macOS.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==6.0.0
    
    - name: Build Linux executable
      run: |
        pyinstaller --onefile --windowed --name "GoogleTakeoutHelper" --add-data "src/google_takeout_live_photos:google_takeout_live_photos" src/google_takeout_live_photos/gui_app.py
    
    - name: Upload Linux executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} dist/GoogleTakeoutHelper
