name: Build and Upload Executables

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build GUI binaries (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            py: '3.11'
            gui: true
          - os: macos-latest
            py: '3.11'
            gui: true
          - os: windows-latest
            py: '3.11'
            gui: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip wheel setuptools

      - name: Install build deps
        run: |
          python -m pip install pyinstaller

      - name: Install Tk dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Show Python version
        run: python -V

      # Fetch ExifTool per OS and place under src/google_takeout_live_photos/vendor/exiftool
      - name: Fetch ExifTool (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libimage-exiftool-perl
          mkdir -p src/google_takeout_live_photos/vendor/exiftool
          cp "$(command -v exiftool)" src/google_takeout_live_photos/vendor/exiftool/exiftool
          chmod +x src/google_takeout_live_photos/vendor/exiftool/exiftool

      - name: Fetch ExifTool (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install exiftool
          mkdir -p src/google_takeout_live_photos/vendor/exiftool
          cp "$(which exiftool)" src/google_takeout_live_photos/vendor/exiftool/exiftool
          chmod +x src/google_takeout_live_photos/vendor/exiftool/exiftool

      - name: Fetch ExifTool (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install exiftool --yes
          New-Item -ItemType Directory -Force src\google_takeout_live_photos\vendor\exiftool | Out-Null
          $exe = (Get-Command exiftool.exe).Source
          Copy-Item $exe src\google_takeout_live_photos\vendor\exiftool\exiftool.exe -Force

      - name: Build GUI executable (macOS/Linux)
        if: runner.os != 'Windows'
        run: |
          pyinstaller --onefile --paths src --windowed --name google-takeout-helper-gui scripts/launch_gui.py \
            --add-data "src/google_takeout_live_photos/vendor/exiftool/*:exiftool"
        shell: bash
        working-directory: .

      - name: Build GUI executable (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pyinstaller --onefile --paths src --windowed --name google-takeout-helper-gui scripts/launch_gui.py \
            --add-data "src\\google_takeout_live_photos\\vendor\\exiftool\\*;exiftool"
        working-directory: .

      - name: Rename artifacts per-OS
        run: |
          set -e
          OS_NAME=${{ runner.os }}
          mkdir -p dist/upload
          if [ "$OS_NAME" = "Windows" ]; then
            mv dist/google-takeout-helper-gui.exe dist/upload/google-takeout-helper-gui-${{ runner.os }}.exe
          else
            mv dist/google-takeout-helper-gui dist/upload/google-takeout-helper-gui-${{ runner.os }}
          fi
        shell: bash

      - name: Upload assets to GitHub Release
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/upload/*
          tag_name: ${{ github.event.release.tag_name || github.ref_name }}
          fail_on_unmatched_files: false


